name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

steps:
  checkout: &checkout
    - name: Checkout
      uses: actions/checkout@master

  install: &install
    - name: Install
      run: |
        sudo apt-get -y install libsqlite3-dev
        gem install bundler -v '< 2'
        bundle install
        bundle exec appraisal install

jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4.x
          - 2.5.x
          - 2.6.x
          # - 2.7.x                   waiting for https://github.com/actions/setup-ruby/issues/45
          # - truffleruby-19.3.x      waiting for https://github.com/actions/setup-ruby/pull/28
    steps:
      <<: *checkout
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      <<: *install
      - name: Test
        run: bundle exec appraisal rspec

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      <<: *checkout
      - name: Setup Ruby
        uses: actions/setup-ruby@master
        with:
          ruby-version: 2.6.x
          architecture: 'x64'
      <<: *install
      - name: Test and publish code coverage
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec appraisal rspec
