name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - truffleruby
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Install
        run: |
          sudo apt-get -y install libsqlite3-dev
          gem install bundler -v '< 2'
          bundle install
          bundle exec appraisal install
      - name: Test
        run: bundle exec appraisal rspec

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
          architecture: 'x64'
      - name: Install
        run: |
          sudo apt-get -y install libsqlite3-dev
          gem install bundler -v '< 2'
          bundle install
          bundle exec appraisal install
      - name: Test and publish code coverage
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec appraisal rspec
