name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4.x
          - 2.5.3
          - 2.6.0
          - 2.7.0
          - truffleruby
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Install
        run: |
          sudo apt-get -y install libsqlite3-dev
          gem install bundler -v '< 2'
          bundle install
          bundle exec appraisal install
      - name: Test
        run: bundle exec appraisal rspec
